version: "3"
services:
  postgres:
    build:
      dockerfile: ./postgres/Dockerfile
    container_name: bit_chat_app_postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bit_chat_app_db
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    hostname: postgres
    restart: always
    stdin_open: true

  api:
    build:
      dockerfile: ./api/Dockerfile
    container_name: bit_chat_app_api
    ports:
      - 7000:8080
    hostname: api
    tty: true
    depends_on:
      - postgres

  nginx:
    image: nginx
    container_name: bit_chat_app_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - api